#!/usr/bin/env fish

set albumart (playerctl metadata mpris:artUrl | string replace file:// '')
catimg -r 2 $albumart ^ /dev/null
echo (playerctl metadata artist) - (playerctl metadata album)

# show this one first
while sleep 1
  set aa2 (playerctl metadata mpris:artUrl | string replace file:// '')
  if [ "$albumart" != "$aa2" ]
    set albumart $aa2
    clear
    catimg -r 2 $albumart ^ /dev/null
    echo (playerctl metadata artist) - (playerctl metadata album)
  end
end
