#!/usr/bin/env fish

set name $argv[1]

mkdir -p $name
cd $name

touch $name.js $name.module.css $name.stories.js
echo >$name.js "\
import React from 'react';

import cx from '../../utils/classnames.js'
import css from './$name.module.css';

const $name = ({className, ...props}) => (
  <div className={cx(css.root, className)}>
  $name
  </div>
);

export default $name;"

echo >$name.module.css "\
.root {
}"

echo >$name.stories.js "\
import React from 'react';

import $name from './$name';
import { storiesOf } from '@storybook/react';

storiesOf('$name', module)
  .add('$name', () => <$name />);"

