#!/usr/bin/bash
exec 2> /dev/null

player=$(playerctl -l | head -n1)
status=$(playerctl status)

if [ "$status" = "Stopped"  -o -z "$status" ]; then
  echo ""
  exit
fi

title=$(playerctl -p $player metadata title | tr -s ' ' | awk 'length > 40{$0=substr($0,0,41)"..."}1')
artist=$(playerctl -p $player metadata artist)

ic=

if [ "$status" = "Playing" ]; then
  ic=
fi

if [ "$artist" != "" ]; then
  echo -n "$ic $artist - "
fi

echo -n "$title"
