#!/usr/bin/env fish

if set -q $argv
  exit 1
end
set walld $HOME/.cache/wallpapers
set colors $HOME/.cache/wal/colors.Xresources
set xfce_theme_file "$HOME/.local/share/xfce4/terminal/colorschemes/wal.theme"
set termite_conf "$HOME/.config/termite/config"

rm -rf $walld
mkdir -p $walld
set pic $argv[1]
cp $pic $walld
betterlockscreen -u $walld

sudo mkdir -p /usr/share/locker
sudo chown $USER:$USER /usr/share/locker/ -R
rm -f /usr/share/locker/*
cp $walld/* /usr/share/locker/
cp $pic /usr/share/locker/lockerImage
chmod 755 /usr/share/locker/ -R

wal -i $pic -n
echo Generating GTK theme...
/opt/oomox/plugins/theme_materia/materia-theme/change_color.sh -o wal $HOME/.cache/wal/colors-oomox > /dev/null
/opt/oomox/plugins/icons_papirus/change_color.sh -o wal $HOME/.cache/wal/colors-oomox > /dev/null
sudo rsync $HOME/.themes/wal /usr/share/themes/ -ah
sudo rsync $HOME/.icons/wal /usr/share/icons/ -ah

sed -i '/!!##/q' $HOME/.Xresources
cat $colors | tee -a $HOME/.Xresources > /dev/null
xrdb -merge $HOME/.Xresources
echo Copied Pywal colors to Xresources

set xfce (termcolors -i xresources -o xfce < $HOME/.Xresources)
set termite (termcolors -i xresources -o termite < $HOME/.Xresources)

printf "%s\n" $xfce | tee $xfce_theme_file > /dev/null
sed -i 's|^\[Conf.*\]$|[Scheme]\nName=0WAL|' $xfce_theme_file
xfce4-color-switch wal
echo Xresources converted to XFCE Terminal

sed -i '/##!!/q' $termite_conf
printf "%s\n" $termite | tee -a $termite_conf > /dev/null
echo Added theme to Termite

cat $HOME/.cache/wal/colors-dunst | tee $HOME/.config/dunst/dunstrc > /dev/null
echo Created dunstrc

betterlockscreen -w $argv[2]
echo Wallpaper set to \'$pic\'
