#!/usr/bin/env fish
set whitelist sg uk us hk

set stat (nordvpn status | grep Status | sed 's/.*:\ //g' | head -n1)

function _confirm
  zenity --question --text $argv
  echo -n "$status"
end

if [ "$stat" = "Disconnected" ]
  echo -n ""
end

if [ "$stat" = "Connecting" ]
  echo -n "..."
end

if [ "$stat" = "Connected" ]
  echo -n ""
  set ln2 (nordvpn status | grep Current\ server | sed 's/.*:\ //g')
  set server (echo $ln2 | sed  's/.//3g')
  echo -n " $server"
end

if [ "$argv" = "toggle" ]
  if [ "$stat" = "Connected" ]
    set ret (_confirm "Do you want to disconnect NordVPN?")
    if [ $ret -eq 0 ]
      nordvpn d
    end
  end
  if [ "$stat" = "Disconnected" ]
    set i (random 1 4)
    set ret (_confirm "Do you want to connect to NordVPN ("$whitelist[$i]")?")
    if [ $ret -eq 0 ]
      nordvpn c $whitelist[$i] > ~/.vpnstat.log &
      disown
    end
  end
end
