#!/usr/bin/env fish
set wh hk jp us uk sg
set stat (nordvpn status | grep Status | sed 's/.*:\ //g' | head -n1)

function confirm
  zenity --question --text=$argv[1]
  echo "$status"
end

if [ "$stat" = "Disconnected" ]
  echo -n ""
end

if [ "$stat" = "Connecting" ]
  echo -n "..."
end

if [ "$stat" = "Connected" ]
  echo -n ""
  set ln2 (nordvpn status | grep Current\ server | sed 's/.*:\ //g')
  set server (echo $ln2 | sed  's/.//3g')
  echo -n " $server"
end

if [ "$argv" = 'toggle' ]
  if [ "$stat" = "Connected" ]
    set ret (confirm "Do you want to disconnect NordVPN?")
    if [ $ret -eq 0 ]
      nordvpn d
    end
  end
  if [ "$stat" = "Disconnected" ]
    set ret (confirm "Do you want to connect to NordVPN?")
    if [ $ret -eq 0 ]
      set i (random 1 5)
      nordvpn c $wh[$i] &
      disown
    end
  end
end
