swipe:
  3: 
    left: 
      command: 'i3-msg workspace prev'
      interval: 1
    right: 
      command: 'i3-msg workspace next'
      interval: 1
    up: 
      command: 'xdotool key ctrl+plus'
    down: 
      command: 'xdotool key ctrl+minus'
pinch:
  2:
    in:
      command: 'xdotool key ctrl+plus'
    out:
      command: 'xdotool key ctrl+minus'

threshold:
  swipe: 0.1
  pinch: 0.1

interval:
  swipe: 0.25
  pinch: 0.25
